import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 30;

import { getObjectMetadata } from "@/lib/r2/get";
import { commitMetadataFiles } from "@/lib/git/commit";
import { getMetadataYaml } from "@/lib/datasets/read";

interface MetadataYaml {
  title: string;
  description: string;
  category: string;
  tags: string[];
  source: string;
  source_url: string;
  confidence: "high" | "medium" | "low";
  format: "csv" | "xlsx";
  filename: string;
}

interface DictionaryEntry {
  column: string;
  type: "string" | "number" | "date" | "boolean" | "category";
  unit: string;
  description: string;
}

interface CommitRequest {
  fileId: string;
  r2Key: string;
  metadata: MetadataYaml;
  dictionary: DictionaryEntry[];
}

/**
 * Convert slug từ title (Vietnamese-safe).
 * "GRDP 34 Tỉnh 2024" → "grdp-34-tinh-2024"
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip diacritics
    .replace(/đ/g, "d")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60);
}

/**
 * Suffix slug với -2, -3, ... nếu đã tồn tại trong repo.
 */
async function resolveUniqueSlug(baseSlug: string): Promise<string> {
  let candidate = baseSlug;
  let suffix = 2;
  // Giới hạn retry để tránh infinite loop
  while (suffix < 100) {
    const existing = await getMetadataYaml(candidate);
    if (!existing) return candidate;
    candidate = `${baseSlug}-${suffix}`;
    suffix++;
  }
  return `${baseSlug}-${Date.now()}`;
}

/**
 * Render metadata.yaml content — extend từ version preview-only để include
 * `version_id` + `sha256` từ R2 object metadata (Approach A refined).
 *
 * Atomic semantics: mỗi commit metadata = snapshot của
 * (description text + exact data version qua version_id).
 */
function renderMetadataYaml(
  meta: MetadataYaml,
  slug: string,
  r2Key: string,
  r2Meta: { version_id?: string; sha256?: string; size_mb?: number }
): string {
  const today = new Date().toISOString().slice(0, 10);
  const tagsYaml =
    meta.tags.length > 0
      ? `\n${meta.tags.map((t) => `  - ${t}`).join("\n")}`
      : " []";
  const versionLine = r2Meta.version_id
    ? `\n    version_id: "${r2Meta.version_id}"`
    : "";
  const shaLine = r2Meta.sha256 ? `\n    sha256: "${r2Meta.sha256}"` : "";
  const sizeLine =
    r2Meta.size_mb !== undefined
      ? `\n    size_mb: ${r2Meta.size_mb}`
      : "";

  return `# metadata.yaml — generated by Upload Wizard
title: "${meta.title}"
slug: "${slug}"
description: "${meta.description}"
category: ${meta.category}
tags:${tagsYaml}
source:
  name: "${meta.source}"
  url: "${meta.source_url || ""}"
  retrieved: "${today}"
  method: manual_entry
license: internal
format: ${meta.format}
confidence: ${meta.confidence}
uploaded_by: demo
uploaded_at: "${new Date().toISOString()}"
files:
  - filename: "${meta.filename}"
    path: "${slug}/${meta.filename}"
    r2_key: "${r2Key}"${versionLine}${shaLine}${sizeLine}
`;
}

/**
 * Render dictionary.md content (markdown table).
 */
function renderDictionaryMarkdown(entries: DictionaryEntry[]): string {
  if (entries.length === 0) {
    return `# Dictionary\n\nDataset ${"không có column (non-tabular hoặc chưa inspect)."}\n`;
  }

  const header =
    "| Column | Type | Unit | Description |\n|--------|------|------|-------------|";
  const rows = entries
    .map((e) => `| \`${e.column}\` | ${e.type} | ${e.unit || "-"} | ${e.description || ""} |`)
    .join("\n");

  return `# Dictionary\n\n${header}\n${rows}\n`;
}

export async function POST(req: NextRequest) {
  let body: CommitRequest;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: "Body phải là JSON hợp lệ" },
      { status: 400 }
    );
  }

  const { fileId, r2Key, metadata, dictionary } = body;

  if (!metadata?.title || !metadata?.description) {
    return NextResponse.json(
      { error: "Metadata thiếu title hoặc description" },
      { status: 400 }
    );
  }

  // 1. Generate unique slug (check conflict trong repo)
  const baseSlug = slugify(metadata.title);
  if (!baseSlug) {
    return NextResponse.json(
      { error: "Không generate được slug từ title" },
      { status: 400 }
    );
  }
  const slug = await resolveUniqueSlug(baseSlug);

  // 2. Fetch R2 object metadata (version_id, sha256, size_mb)
  let r2Meta: {
    version_id?: string;
    sha256?: string;
    size_mb?: number;
  } = {};
  try {
    const full = await getObjectMetadata(r2Key);
    r2Meta = {
      version_id: full.version_id,
      sha256: full.sha256,
      size_mb: full.size_mb,
    };
  } catch (err) {
    console.warn("[commit] R2 metadata fetch thất bại:", err);
    // Continue — fields optional trong metadata.yaml
  }

  // 3. Render YAML + markdown content
  const yamlContent = renderMetadataYaml(metadata, slug, r2Key, r2Meta);
  const markdownContent = renderDictionaryMarkdown(dictionary ?? []);

  // 4. Git commit + push metadata.yaml + dictionary.md
  let commitResult;
  try {
    commitResult = await commitMetadataFiles(
      slug,
      yamlContent,
      markdownContent
    );
  } catch (err) {
    console.error("[commit] Git push thất bại:", err);
    const message = err instanceof Error ? err.message : "Unknown error";
    return NextResponse.json(
      {
        error: `Không commit được metadata lên GitHub: ${message}`,
        slug,
        yamlPreview: yamlContent,
        markdownPreview: markdownContent,
        committed: false,
      },
      { status: 500 }
    );
  }

  console.info("[commit] Dataset đã publish:", {
    slug,
    commitSha: commitResult.commitSha,
    r2Key,
    r2VersionId: r2Meta.version_id,
  });

  return NextResponse.json({
    slug,
    yamlPreview: yamlContent,
    markdownPreview: markdownContent,
    committed: true,
    commitSha: commitResult.commitSha,
    commitUrl: commitResult.commitUrl,
    url: `/datasets/${slug}`,
    message: `Dataset đã publish tại /datasets/${slug}.`,
  });
}
