import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 30;

interface MetadataYaml {
  title: string;
  description: string;
  category: string;
  tags: string[];
  source: string;
  source_url: string;
  confidence: "high" | "medium" | "low";
  format: "csv" | "xlsx";
  filename: string;
}

interface DictionaryEntry {
  column: string;
  type: "string" | "number" | "date" | "boolean" | "category";
  unit: string;
  description: string;
}

interface CommitRequest {
  fileId: string;
  r2Key: string;
  metadata: MetadataYaml;
  dictionary: DictionaryEntry[];
}

/**
 * Convert slug từ title (Vietnamese-safe).
 * "GRDP 34 Tỉnh 2024" → "grdp-34-tinh-2024"
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "") // strip diacritics
    .replace(/đ/g, "d")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 60);
}

/**
 * Render metadata.yaml content (string) từ metadata object.
 * KHÔNG dùng yaml package — hand-roll để giữ output stable, không thêm dependency.
 */
function renderMetadataYaml(meta: MetadataYaml, slug: string, r2Key: string): string {
  const today = new Date().toISOString().slice(0, 10);
  const tagsYaml = meta.tags.length > 0 ? `\n${meta.tags.map((t) => `  - ${t}`).join("\n")}` : " []";

  return `# metadata.yaml — generated by Upload Wizard MVP (preview-only)
title: "${meta.title}"
slug: "${slug}"
description: "${meta.description}"
category: ${meta.category}
tags:${tagsYaml}
source:
  name: "${meta.source}"
  url: "${meta.source_url || ""}"
  retrieved: "${today}"
  method: manual_entry
license: internal
format: ${meta.format}
confidence: ${meta.confidence}
uploaded_by: demo
uploaded_at: "${new Date().toISOString()}"
files:
  - path: "${slug}/${meta.filename}"
    r2_key: "${r2Key}"
    size_mb: unknown
`;
}

/**
 * Render dictionary.md content (markdown table).
 */
function renderDictionaryMarkdown(entries: DictionaryEntry[]): string {
  if (entries.length === 0) {
    return "# Dictionary\n\nKhông có column nào.\n";
  }

  const header = "| Column | Type | Unit | Description |\n|--------|------|------|-------------|";
  const rows = entries
    .map((e) => `| \`${e.column}\` | ${e.type} | ${e.unit} | ${e.description} |`)
    .join("\n");

  return `# Dictionary\n\n${header}\n${rows}\n`;
}

export async function POST(req: NextRequest) {
  let body: CommitRequest;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: "Body phải là JSON hợp lệ" },
      { status: 400 }
    );
  }

  const { fileId, r2Key, metadata, dictionary } = body;

  if (!metadata?.title || !metadata?.description) {
    return NextResponse.json(
      { error: "Metadata thiếu title hoặc description" },
      { status: 400 }
    );
  }

  const slug = slugify(metadata.title);
  if (!slug) {
    return NextResponse.json(
      { error: "Không generate được slug từ title" },
      { status: 400 }
    );
  }

  // Render preview content
  const yamlContent = renderMetadataYaml(metadata, slug, r2Key);
  const markdownContent = renderDictionaryMarkdown(dictionary ?? []);

  // ⚠️ MVP: PREVIEW-ONLY — KHÔNG git push, KHÔNG move R2 object
  // Build chunk sau sẽ wire GITHUB_TOKEN + git push metadata + R2 move staging → final
  console.info("[commit] would commit", {
    slug,
    fileId,
    r2Key,
    metadataSize: yamlContent.length,
    dictionarySize: markdownContent.length,
  });

  return NextResponse.json({
    slug,
    yamlPreview: yamlContent,
    markdownPreview: markdownContent,
    committed: false, // flag rõ cho frontend
    message: "Đây là preview. Metadata chưa được commit (sẽ có trong build chunk sau).",
  });
}
